# The Battle of the Neighborhoods (Week 1)

## Problem

The world has gotten a lot smaller and it is a lot easier for people to travel the world and move to a new place. A lot of employers also require nowadays that you have international experience. Imagine you are a young professional, single and you move to Austin, TX for a year. You want to have the best experience possible. The thing is that you need to find a place to live. Which neighborhood though!? Of course you want to move somewhere safe. It should also have great restaurants or bars to meet people.

The problem: Where in Austin should you move to where neighborhoods are save and you have great venues?

## Data

I'm using the foursquare location data for 5 top venues, similar to the New York and Toronto analysis. Additionally I downloaded the Austin Crime Report Data 2018 from https://data.austintexas.gov/Public-Safety/Crime-Reports-2018/vmn9-3bvu to make a crime heat map of Austin. I will also create graphics that show when most crimes appear and what type of crimes. The Crime Report Data includes longitude and latitude, is in .csv format, so it can easly be read in with pandas and merged with the foursquare location data. I will use the getNearbyVenues function from the labs to access Austin venues from foursquarre.

In [1]:
import pandas as pd
crime_df = pd.read_csv("W:/Crime_Reports_2018.csv")
crime_df.head()

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
0,2.018365e+10,DEADLY CONDUCT,408,N,12/31/2018 23:54,12/31/2018,2354,12/31/2018 23:54,12/31/2018,2354,...,18.04,NaN,NaN,13A,Aggravated Assault,3125118.0,3125118.0,30.339849,-97.706618,"(30.33984945, -97.70661753)"
1,2.018365e+10,POSSESSION OF MARIJUANA,1803,N,12/31/2018 23:46,12/31/2018,2346,12/31/2018 23:46,12/31/2018,2346,...,1.01,C,1/1/2019,NaN,NaN,3110934.0,3110934.0,30.309252,-97.752412,"(30.30925222, -97.752412)"
2,2.018365e+10,FAMILY DISTURBANCE,3400,N,12/31/2018 23:32,12/31/2018,2332,12/31/2018 23:32,12/31/2018,2332,...,17.61,N,1/6/2019,NaN,NaN,3082798.0,3082798.0,30.391518,-97.839473,"(30.39151787, -97.83947264)"
3,2.018365e+10,ASSAULT WITH INJURY,900,N,12/31/2018 23:25,12/31/2018,2325,12/31/2018 23:44,12/31/2018,2344,...,21.12,N,1/21/2019,NaN,NaN,3132665.0,3132665.0,30.321537,-97.683190,"(30.32153667, -97.68318973)"
4,2.018365e+10,DATING DISTURBANCE,2400,N,12/31/2018 23:20,12/31/2018,2320,12/31/2018 23:47,12/31/2018,2347,...,12.00,N,1/27/2019,NaN,NaN,3108247.0,3108247.0,30.273213,-97.761890,"(30.2732126, -97.76188976)"